spring.application.name=SERVICIO-PRODUCTOS

# Donde esta el servidor Eureka
eureka.client.service-url.defaultZone=http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

# Configuracion de la BD vidrieria
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# redis
spring.data.redis.host=redis-cache
spring.data.redis.port=6379

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# Control de logs
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

spring.jpa.open-in-view=false
logging.level.org.hibernate.orm.connections.pooling=ERROR
logging.level.org.hibernate.engine.jdbc=ERROR

# Configuracion general
server.port=8081
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.jackson.time-zone=America/Lima

#Spring email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${SMTP_USER}
spring.mail.password=${SMTP_PASS}
spring.mail.properties.mail.smtp.ssl.enable = true
spring.mail.properties.mail.smtp.auth = true


# CLAVE DE SEGURIDAD JWT
jwt.secret=${JWT_SECRET}

# Oculta el warning de la contrase de seguridad generada
logging.level.org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration=ERROR

spring.devtools.livereload.enabled=false

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

management.endpoints.web.exposure.include=prometheus,health,info
management.server.port=${server.port}
# CONFIGURACIÓN MVC MULTIPART
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB