spring.main.web-application-type=reactive
server.port=8000
spring.application.name=SERVICIO-GATEWAY

# ------------------------------
#  EUREKA
# ------------------------------
eureka.client.service-url.defaultZone=http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

spring.cloud.gateway.routes[0].id=servicio-usuarios-login
spring.cloud.gateway.routes[0].uri=lb://SERVICIO-USUARIOS
spring.cloud.gateway.routes[0].predicates[0]=Path=/login/**

spring.cloud.gateway.routes[1].id=servicio-usuarios-gestion
spring.cloud.gateway.routes[1].uri=lb://SERVICIO-USUARIOS
spring.cloud.gateway.routes[1].predicates[0]=Path=/usuarios/**
spring.cloud.gateway.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.name=usuariosCircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.fallbackUri=forward:/fallback/usuarios

spring.cloud.gateway.routes[2].id=servicio-inventario
spring.cloud.gateway.routes[2].uri=lb://SERVICIO-INVENTARIO
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/**
spring.cloud.gateway.routes[2].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[2].filters[0].args.name=inventarioCircuitBreaker
spring.cloud.gateway.routes[2].filters[0].args.fallbackUri=forward:/fallback/inventario

spring.cloud.gateway.routes[3].id=servicio-media
spring.cloud.gateway.routes[3].uri=lb://SERVICIO-PRODUCTOS
spring.cloud.gateway.routes[3].predicates[0]=Path=/media/**

spring.cloud.gateway.routes[4].id=servicio-productos
spring.cloud.gateway.routes[4].uri=lb://SERVICIO-PRODUCTOS
spring.cloud.gateway.routes[4].predicates[0]=Path=/catalogo/**
spring.cloud.gateway.routes[4].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[4].filters[0].args.name=productosCircuitBreaker
spring.cloud.gateway.routes[4].filters[0].args.fallbackUri=forward:/fallback/productos

# ============================================================
# RESILIENCE4J
# ============================================================
resilience4j.circuitbreaker.instances.inventarioCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventarioCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventarioCircuitBreaker.waitDurationInOpenState=10000
resilience4j.timelimiter.instances.inventarioCircuitBreaker.timeoutDuration=4s

# ============================================================
# MONITOREO
# ============================================================
management.endpoints.web.exposure.include=prometheus,health,info

# vidrieria-api_gateway/src/main/resources/application.properties

# Aumenta la capacidad de memoria del codec para peticiones entrantes grandes (WebFlux)
spring.codec.max-in-memory-size=10MB

# Establece los límites de archivo (por si acaso)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB